import { Bot, User } from "lucide-react";

export default function ChatMessage({ text, sender, modelUsed }) {
  const isAi = sender === "ai";

  return (
    <div className={`message-wrapper ${isAi ? "ai-message" : "user-message"}`}>
      <div className="avatar">
        {isAi ? <Bot size={20} /> : <User size={20} />}
      </div>
      <div className="message-content">
        <p>{text}</p>
        {isAi && modelUsed && (
          <span className="model-badge">Generated by {modelUsed}</span>
        )}
      </div>
    </div>
  );
}
